default:
  site:
    review_period: "13 months"
    spaces:
      - space_path: rest-api
        space_name: REST API
    branch: master
    dev_browser_path: rest-api
    versions:
      - label: FT
        is_current_version: true
      - label: "2.8"
        url_path: "2.8"
  verify_paths:
    - index.html
development:
  isDev: true
